language: cpp
compiler: gcc
dist: trusty
before_install:
# C++14
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install: 
# C++14
- sudo apt-get install -qq g++-6
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
before_script:
- sudo apt-get install libboost-test-dev -y
script:
# Install Boost Test Framework 1.54
#- sudo apt-get install -y -qq libboost-test1.54-dev
#- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release .
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_print-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -umohammadwolf95:$BINTRAY_API_KEY "https://api.bintray.com/content/mohammadwolf95/ip_print/ip_print/$TRAVIS_BUILD_NUMBER/ip_print-0.0.$TRAVIS_BUILD_NUMBER-Liux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
 
